### ISSUE TITLE
Title area is hidden and requires scroll to see it.

### ISSUE THREAD

**Issue by korontari** [BWPanda/featherlight#4]
If image is large enough the title is hidden below and scroll control appears on the right side. To see the title user needs to scroll down.
Expected behaviour: image is displayed a bit smaller so that title is visible and no scrolling controls required.

![2018-11-15_16-35-56](https://user-images.githubusercontent.com/44873997/48642750-d16efc00-e9ee-11e8-8128-5735b950695f.png)

**Comment by ghost** [comment]
I've made a PR that attempts to fix this. Could you please try it out and see if if works for you? If possible, could you also please test to see how easy it is to override if you want to, say, display the caption on top of the image?

**Comment by korontari** [comment]
I have tested featherlight-issue-4 and it appears that title is now visible without scrolling and seem to be placed correctly but the scroll bar is still there. It looks like the size of image frame/container hasn't changed and there is a blank space below image title that causes scrolling.
![2018-11-20_19-58-12](https://user-images.githubusercontent.com/44873997/48790028-7c3d2e00-ecff-11e8-8ffd-05ef413b8822.png)

**Comment by korontari** [comment]
Not sure what you mean about overriding to place title on top of the image. If you mean some CSS coding then I think I am of little help here as I am a designer, not a programmer, and have a very basic understanding of CSS. :)

**Comment by ghost** [comment]
Hmmm, my testing didn't show the scrollbar any more. Is your site live that I can view it somehow? If not, I'll try testing this again myself when I get a chance.

**Comment by korontari** [comment]
Yes, the site is accessible and here is the link to the gallery:  http://bd.goloviy.com/gallery.

**Comment by ghost** [comment]
@korontari Have you done anything to fix this? I've just checked your site and I can't see any scrollbars...

**Comment by korontari** [comment]
No, I didn't do anything to fix it. All I did is I cleared cache in browser (Chrome) and in Configuration->Development->Performance. And I still see scrollbars. If I scroll to the bottom there is an extra white space appears from below.
![2018-11-21_11-50-59](https://user-images.githubusercontent.com/44873997/48830010-aab11c80-ed84-11e8-9d84-cf7884168262.png)

**Comment by korontari** [comment]
A few more notes about title area. When viwed on a mobile device and if there is enough screen space below, the scroll bar doesn't appear and that extra white space is visible.
![photo_2018-11-22_19-21-46](https://user-images.githubusercontent.com/44873997/48919339-433dbe80-eea3-11e8-92f7-24874cf5ba46.jpg)
The scroll bar appears when image frame is close to top and bottom edges of screen/browser and in my case it happened when screen changed orientation from vertical to horizontal.

I also noticed a bug on mobile devices. When screen orientation is changed, say, from vertical to horizontal, and then back to vertical then image is dispalyed stretched.
![photo_2018-11-22_19-21-45](https://user-images.githubusercontent.com/44873997/48919542-64eb7580-eea4-11e8-94d9-18876a6aff15.jpg)

**Comment by ghost** [comment]
Thanks for the feedback. I've updated the PR with some styling that displays the caption on top of the image and should therefore fix the scrolling issue. Please test and let me know how that works for you.

**Comment by korontari** [comment]
Well, it definitely better than having a scroll bar on a side. But for me this is still not a very good solution as it obscures part of the image. For some images (if not the most) it may be critical as it affects the composition and the way it is perceived by the viewer.  It is really important to avoid any UI items placed over image that is being displayed.

**Comment by korontari** [comment]
Here is an example to demonstrate how UI elements can obstract seeing a picture:
![photo_2018-11-25_14-33-48](https://user-images.githubusercontent.com/44873997/48978621-35648500-f0bf-11e8-8c29-050e2dd07147.jpg)

**Comment by ghost** [comment]
This is purely done with CSS, so you're welcome to change it as necessary for your site. If you know of a better way to show the title that doesn't cover the image but that also doesn't cause scrollbars, I'm all ears. But this was the only way I found that didn't result in scrollbars...

**Comment by korontari** [comment]
I understand. I will try to do that though I doubt my CSS skill are even close to yours. )
